#!/usr/bin/env bash
# Read the man page for this script by running perldoc on it.

# Stop the script if any command exits with non-zero exit status and
# isn't caught (e.g. by && or ||).
set -e

# Error if any variables are undefined.
set -u

# error "error string"
# Given a string, outputs the string and exits the script with a non-zero
# status.  Used to report errors.  The script will exit before error exits
# with non-zero status, and set -e above will then abort the script.
#
# Example
# do_something || error "something failed!"
#
error() {
    echo "$@" >&2
    exit 1
}

# When you change this, change the POD docs below too, and vice versa
USAGE="usage: $(basename "$0") subject of inbox entry"

# Parse command line options.
# Colon after a letter means it has an argument, otherwise it's a flag.
# e.g. "d:" means you expect "-d arg", "v" means you expect "-v".
while getopts hv OPT; do
    case "$OPT" in
        h)  # help
            perldoc "$0"
            exit 0
            ;;
        v) # script version
            echo "$(basename "$0") version 0.1"
            exit 0
            ;;
        \?) # Unexpected argument - usage error
            # getopts issues an error message
            echo "$USAGE" >&2
            exit 1
            ;;
    esac
done

# Remove the switches we parsed above.
shift $((OPTIND - 1))

# Access additional arguments as usual through
# variables $@, $*, $1, $2, etc.

# Script goes here

inbox_dir="$(gtd config read inbox_directory)"

test "$inbox_dir" || \
    error "Inbox directory not configured. Please run gtd init."

test -d "$inbox_dir" || \
    error "Inbox directory $inbox_dir does not exist. Please run mkdir -p " \
        "\"$inbox_dir\" if this is the correct directory, or edit your gtd " \
        "configuration file if it is incorrect."

if [ "$*" ] ; then
    filename="$(echo "$*" | tr "[:upper:]" "[:lower:]" | sed 's/ /_/g')".txt
else
    filename="$(date +%F-%H-%M-%S)".txt
fi

test "$EDITOR" || EDITOR="nano"

$EDITOR "$inbox_dir/$filename"

# Docs. Read by runing perldoc on this file
: <<END_OF_DOCS
=head1 NAME

gtd-i - Add an item as a text file to your GTD inbox

=head1 SYNOPSIS

    # Create and edit a file named "build_lunar_base.txt" in your inbox
    gtd-i Build Lunar Base

=head1 OPTIONS

=head1 DESCRIPTION

C<gtd-i> is a convenience script that lets you quickly add an item to your
inbox from the command line. e.g., typing C<gtd i talk with joe> will open up
your favorite editor with an empty file named "talk_with_joe.txt" in whatever
directory your GTD inbox is configured to be in (e.g. ~/Dropbox/Inbox).

If your directory hasn't been configured, run C<gtd init> to set up your
directories.

All command-line arguments are concatinated, converted to lower case, and
spaces are replaced with underlines.

=cut
END_OF_DOCS

